/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ironmanscetch.gltf --transform 
Files: ironmanscetch.gltf [2.23MB] > ironmanscetch-transformed.glb [1.73MB] (23%)
Author: chanchanradin (https://sketchfab.com/chanchanradin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ironman-gemini-printable-warmachine-batman-cc2be2bfaefb481e83aa39d06610ecd4
Title: Ironman-gemini-printable-warmachine-batman-
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ironmanscetch-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/ironmanscetch-transformed.glb')
