/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ironman.gltf --transform 
Files: ironman.gltf [217.27MB] > ironman-transformed.glb [12.61MB] (94%)
Author: 9A Films / Nihar Arora (https://sketchfab.com/Nihar-9Afilms)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iron-man-mark-85-rigged-dde1085c464d4f8da259fe6669ae4dd2
Title: Iron-Man Mark 85 | Rigged
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ironman-transformed.glb')
    let scaleNumber=0.8
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.Silver_Part} skeleton={nodes.Object_6.skeleton} scale={scaleNumber} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Silver_Part} skeleton={nodes.Object_7.skeleton} scale={scaleNumber} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.Silver_Part} skeleton={nodes.Object_8.skeleton} scale={scaleNumber} />
      <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.Arc_Reactor} skeleton={nodes.Object_10.skeleton} scale={scaleNumber} />
      <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.Arc_Reactor} skeleton={nodes.Object_11.skeleton} scale={scaleNumber} />
      <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.Gold_Part} skeleton={nodes.Object_13.skeleton} scale={scaleNumber} />
      <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.Red_Part} skeleton={nodes.Object_15.skeleton} scale={scaleNumber} />
      <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.Red_Part} skeleton={nodes.Object_16.skeleton} scale={scaleNumber} />
      <skinnedMesh geometry={nodes.Object_18.geometry} material={materials.Lights} skeleton={nodes.Object_18.skeleton} scale={scaleNumber} />
      <skinnedMesh geometry={nodes.Object_20.geometry} material={materials.Glass} skeleton={nodes.Object_20.skeleton} scale={scaleNumber} />
    </group>
  )
}

useGLTF.preload('/ironman-transformed.glb')
